---
engines:
  golint:
    enabled: true
  govet:
    enabled: true
  gofmt:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.css"
  - "**.scss"
  - "**.go"
exclude_paths:
  - "frontend/src/styles/mdl.css"
