---
engines:
  golint:
    enabled: true
    exclude_paths:
    - "frontend/**/*"
  govet:
    enabled: true
    exclude_paths:
    - "frontend/**/*"
  gofmt:
    enabled: true
    exclude_paths:
    - "frontend/**/*"
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          paths:
          - "frontend/src/**/*.js"
          - "frontend/test/**/*.js"
          - "frontend/cfg/**/*.js"
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.css"
  - "**.scss"
  - "**.go"
exclude_paths:
  - "frontend/src/styles/mdl.css"
  - "frontend/node_modules/**/*"
