engines:
  golint:
    enabled: true
  govet:
    enabled: true
  gofmt:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.css"
  - "**.go"
